# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 10:04
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171223_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(upload_to=api.models.UploadToUUIDPath('/home/fahmi/velosa/prakkul/pw/bcak/media/tutorial/video'), validators=[api.models.FileValidator(content_types=('video/mp4', 'video/webm', 'video/ogg'))]),
        ),
    ]
