# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 14:48
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171223_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='buyers',
        ),
        migrations.AlterField(
            model_name='illustration',
            name='image',
            field=models.ImageField(upload_to=api.models.UploadToUUIDPath('media/tutorial/illustration/')),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(upload_to=api.models.UploadToUUIDPath('media/user/payment_proof/')),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='banner',
            field=models.ImageField(upload_to=api.models.UploadToUUIDPath('media/tutorial/banner/')),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(upload_to=api.models.UploadToUUIDPath('media/tutorial/video/'), validators=[api.models.FileValidator(content_types=('video/mp4', 'video/webm', 'video/ogg'))]),
        ),
    ]
